version: '3'
services:
  python: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atma10
    ports:
    - "8080:8888"
    volumes:
    - .:/workdir
    environment:
    - PYTHONPATH=/workdir
    command: 
      jupyter lab
        --ip=0.0.0.0
        --port=8888
        --allow-root
        --no-browser
        --NotebookApp.token=''
        --notebook-dir=/workdir